# Welcome to Jekyll!

title: Everything's swirling
email: andy@grange85.co.uk
description: > 
  It's what I am.
baseurl: "/swirling" 
url: "https://www.grange85.co.uk" 
theme: no-style-please
theme_config:
  appearance: "dark"
  back_home_text: "<-- back to home"
  date_format: "%Y-%m-%d"
  show_description: true

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed

jekyll-compose:
  auto_open: true
  default_front_matter:
    drafts:
      layout: post
      title: 
      imgurl: 
      author:
        display_name: Andy
        login: admin
        email: andy@grange85.co.uk
      categories:
       - 
      tags:
       - 
    posts:
      layout: post
      title: 
      imgurl:
      author:
        display_name: Andy
        login: admin
        email: andy@grange85.co.uk
      categories:
       - 
      tags:
       - 



excerpt_separator: <!--more-->

# Build settings
version: 4.2.0
host: 0.0.0.0
port: 4050
markdown: kramdown
plugins: [
        ]
        
exclude: [
    '_notes',
    'Gemfile',
    'Gemfile.lock',
    'Rakefile',
    '.sass-cache',
    '.git',
    's3cfg-prog',
    's3cfg-prog.enc',
    'config',
    'vendor',
    'deploy.sh',
    '_deploy',
    '_cloudfront-distriution-id'
  ]
keep_files:
  - images
excerpt_separator: <!--more-->
