#  Site settings
title: Everything's swirling

author: Andy Aldridge
email: andy@grange85.co.uk
url: https://www.grange85.co.uk 
domain: 
description: > 
  It's what I am.
baseurl: "" 
url: "https://www.grange85.co.uk" 
theme: no-style-please
theme_config:
  appearance: "light"
  back_home_text: "<-- back to home"
  date_format: "%Y-%m-%d"
  show_description: true

plausible_domain: "grange85.co.uk"
goat_counter: grange85
permalink: /swirling/:year/:month/:day/:title/

plugins:
  - jekyll-feed

main_categories:
  - 50 albums
  - 60 albums
  - a head full of wishes
  - btvs
  - christmas
  - film
  - hitchcock
  - living by the water
  - misc
  - music
  - photography
  - sport

jekyll_compose:
  auto_open: true
  default_front_matter:
    drafts:
      layout: post
      sitemap: true
      series-title: 
      github-comments-issueid: 
      author: 
        display_name: Andy
        login: admin
        email: andy@grange85.co.uk
        url: https://www.grange85.co.uk
      image:
      categories:
       - 
      tags: 
       - 
    posts:
      layout: post
      sitemap: true
      series-title: 
      github-comments-issueid: 
      author:
        display_name: Andy
        login: admin
        email: andy@grange85.co.uk
        url: https://www.grange85.co.uk
      image: 
      categories:
       - 
      tags:
       - 

# Build settings
livereload: false
host: 0.0.0.0
port: 4050
markdown: kramdown
environment: production
future: false
        
# default excludes
exclude:
  - vendor
  - _notes
  - Rakefile
  - .git
  - config
  - _deploy
  - _site
  - .jekyll-cache
  - "*.swp"
  - "*.swo"
  - "*.swn"

keep_files:
  - images

plugins:
  - jekyll-feed
  - jekyll-seo-tag
