# Site settings
title: Everything's swirling
subtitle:
email: andy@grange85.co.uk
baseurl: "/swirling"
url: "https://www.grange85.co.uk"
domain: https://www.grange85.co.uk
description: > # this means to ignore newlines until "baseurl:"
  It's what I am.




 
  
sass:
  sass_dir: _sass
  style: compressed









twitter_username: grange85
github_username:  grange85
permalink: /:year/:month/:day/:title/

jekyll-archives:
  enabled: ['month','categories']
  layouts:
    month: month-archive
    category: category-archive
  permalinks:
    month: '/:year/:month/'
    category: '/category/:name/'



pagination: 
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 5
  permalink: '/page:num/'
  title: ':title - page :num'
  limit: 10
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  trail: 
    before: 2
    after: 2
  extension: html
  indexpage: 'index'

excerpt_separator: <!--more-->

jekyll-compose:
  auto_open: true
  default_front_matter:
    drafts:
      layout: post
      sitemap: true
      series-title:
      author:
        display_name: Andy
        login: admin
        email: andy@grange85.co.uk
        url: https://www.grange85.co.uk
      imageurl: 
      categories:
       - 
      tags:
       - 
    posts:
      layout: post
      series-title: 
      sitemap: true
      author:
        display_name: Andy
        login: admin
        email: andy@grange85.co.uk
        url: https://www.grange85.co.uk
      imageurl:
      categories:
       - 
      tags:
       - 


# Build settings
livereload: false
host: 0.0.0.0
port: 4050
markdown: kramdown
environment: production
future: false
        
exclude: [
    '_notes',
    'Gemfile',
    'Gemfile.lock',
    'Rakefile',
    '.sass-cache',
    '.git',
    'config',
    'vendor',
    'deploy.sh',
    '_deploy',
    '_cloudfront-distriution-id'
  ]
keep_files:
    - images
