name: ES (not size-only)
on:
  workflow_dispatch:
    inputs:
      tags:
        description: manual deploy
jobs:
  deployment:
    runs-on: ubuntu-22.04
    environment:
      name: production
      url: https://www.grange85.co.uk/swirling/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Build site
        run: |
          bundle exec jekyll build --config _config.yml,_config_build.yml
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Sync output to S3
        run: >
          aws s3 sync --delete --exclude '.sass-cache' _deploy s3://www-new.grange85.co.uk/swirling/

          aws cloudfront create-invalidation --no-cli-pager --distribution-id ${{ secrets.CDN_DISTRIBUTION_ID_WWW }} --paths "/swirling/*"

          aws cloudfront create-invalidation --no-cli-pager --distribution-id ${{ secrets.CDN_DISTRIBUTION_ID_CDN }} --paths "/*"
